### ISSUE TITLE
Support for Yarn 1.x.x

### ISSUE THREAD

**Issue by zeitchef** [vuki656/package-info.nvim#104]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no existing ones with the same request.

### Feature description

I'm aware that this was recently removed, as well as the personal opinions regarding Yarn 2 usage, but I personally don't have a lot of choice for work projects which version of Yarn I can use. Might there still be a way to support "legacy" projects that require Yarn 1?

Thanks for the consideration.

### Help

No, sorry.

**Comment by vuki656** [comment]
You're right. I didn't consider all the use cases. I'll put it together over the next few days.

**Comment by Iamafnan** [comment]
Yes please add support for **Yarn v1** as it shows error like when upgrading packages it shows error because package-info uses `yarn up` command to upgrade packages and `yarn up` is not present in v1

**Comment by vuki656** [comment]
I just implemented it in #108 can you please test it and let me know if it works as expected.

I tested it on one of my repos.

**Comment by zeitchef** [comment]
@vuki656 Thanks for your attention to this, but it's still not working for me. It's still trying to use `yarn up` in a Yarn 1 project.

**Comment by vuki656** [comment]
I just pushed a commit that has `print` sprinkled over the functions. Can you pull that and try running the commands and let me know what you get?
