### ISSUE TITLE
[BUG] It does nothing

### ISSUE THREAD

**Issue by pedro757** [vuki656/package-info.nvim#127]
### Issues

- [X] I have checked [existing issues](https://github.com/vuki656/package-info.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.

### Plugin Version

- [X] I am using the latest version of the plugin

### Neovim Version

- [X] I am using the 0.6 neovim version or later

### Neovim Version

v0.8.0-dev+422-g619eb32c7

### Branch

master

### Actual behavior

It's not doing anything, it does not even show the loader in my statusline

### Expected behavior

work

### Steps to reproduce

<details>
  <summary>This is my package.json:</summary>

```json
{
  "name": "ls_emmet",
  "version": "1.0.9",
  "description": "Just emmet completion with LSP",
  "main": "dist/server.js",
  "scripts": {
    "build": "tsc --outDir dist",
    "dev": "npm run build && npm link"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/pedro757/emmet.git"
  },
  "author": "@pedro757",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/pedro757/emmet/issues"
  },
  "homepage": "https://github.com/pedro757/emmet#readme",
  "dependencies": {
    "@types/node": "^17.0.33",
    "emmet": "^2.3.4",
    "typescript": "^4.4.2",
    "vscode-languageserver": "^8.0.1",
    "vscode-languageserver-textdocument": "^1.0.1"
  },
  "bin": {
    "ls_emmet": "dist/server.js"
  },
  "eslintConfig": {
    "root": true,
    "extends": [
      "eslint:recommended",
      "plugin:@typescript-eslint/recommended"
    ],
    "parser": "@typescript-eslint/parser",
    "parserOptions": {
      "project": [
        "./tsconfig.json"
      ]
    },
    "plugins": [
      "@typescript-eslint"
    ],
    "rules": {
      "indent": [
        "error",
        2
      ],
      "max-len": [
        "error",
        {
          "code": 80
        }
      ],
      "no-trailing-spaces": "error"
    }
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.10.1",
    "@typescript-eslint/parser": "^5.10.1"
  }
}

```  
</details>

### Package info config

require("package-info").setup()

### Help

Yes, but I don't know how to start. I would need guidance (check question below)

**Comment by pedro757** [comment]
Now it does not show the previous error but it does nothing

**Comment by vuki656** [comment]
Can you try reloading your terminal? 

I just tried it with your package json file and it works as expected.

**Comment by pedro757** [comment]
I tried but it's still the same

![image](https://user-images.githubusercontent.com/30637426/174320830-33592217-c85d-4cea-82a0-ba18bd13b879.png)
![image](https://user-images.githubusercontent.com/30637426/174320889-6ed4efd6-d966-49e3-989e-674adecbd684.png)

**Comment by vuki656** [comment]
This happens when you run `PackageInfoShow` ?

**Comment by pedro757** [comment]
`is_loaded` is never set to true

![image](https://user-images.githubusercontent.com/30637426/174323345-0d1ed9e9-b021-48a8-87d4-c4ba76f793e3.png)

**Comment by vuki656** [comment]
Oh, that's weird. Is the `autocmd` that sets it even being called?

**Comment by pedro757** [comment]
Oh forget that part, I mistook the seach, but the problem is here I think, because it will return without running the rest of the code

https://github.com/vuki656/package-info.nvim/blob/45e409c69063a057250833a747e52e2ff00dd722/lua/package-info/actions/show.lua#L13-L17

**Comment by princejoogie** [comment]
updated the plugin and it stopped working. getting the error `PackageInfo: Not in valid package.json file` also tried setting autostart: true but still not working

**Comment by zeitchef** [comment]
@vuki656 I'm also getting `PackageInfo: Not in valid package.json file` error

**Comment by vuki656** [comment]
@princejoogie @zeitchef for which command are you getting that message? 

Also, would you mind attaching the relevant `package.json` files?

I'm unable to reproduce the problem and would really like to figure out why it's happening.

**Comment by zeitchef** [comment]
Also `PackageInfoShow` doesn't show anything for me anymore.

**Comment by piersolenski** [comment]
Same issue here 😥

**Comment by vuki656** [comment]
> @vuki656 I first noticed the issue on a work repo, which I can't really share. But I noticed the issue on my personal website as well when trying to `PackageInfoUpdate`:
> 
> ```
> {
>   "version": "1.0.0",
>   "license": "UNLICENSED",
>   "private": true,
>   "scripts": {
>     "dev": "nuxt",
>     "build": "nuxt build",
>     "start": "nuxt start",
>     "generate": "nuxt generate",
>     "test": "jest"
>   },
>   "dependencies": {
>     "@nuxt/content": "^1.15.1",
>     "@nuxtjs/axios": "^5.13.6",
>     "@nuxtjs/content": "^0.3.0",
>     "@nuxtjs/gtm": "^2.4.0",
>     "@nuxtjs/robots": "^2.5.0",
>     "@nuxtjs/sentry": "^5.1.7",
>     "core-js": "^3.21.1",
>     "nuxt": "^2.15.8",
>     "prism-themes": "^1.9.0"
>   },
>   "devDependencies": {
>     "@nuxtjs/color-mode": "2.1.1",
>     "@nuxtjs/google-fonts": "^1.3.0",
>     "@nuxtjs/tailwindcss": "^5.0.2",
>     "@vue/test-utils": "^1.3.0",
>     "babel-core": "7.0.0-bridge.0",
>     "babel-jest": "^27.5.1",
>     "jest": "^27.5.1",
>     "vue-jest": "^3.0.7"
>   }
> }
> ```

I just tried with this package JSON file on my pc and it works as expected. 

It has to be conflicting with something else then.

Would you mind disabling all plugins and trying then? @piersolenski @princejoogie @pedro757 please try as well

**Comment by vuki656** [comment]
> Oh forget that part, I mistook the search, but the problem is here I think, because it will return without running the rest of the code
> 
> https://github.com/vuki656/package-info.nvim/blob/45e409c69063a057250833a747e52e2ff00dd722/lua/package-info/actions/show.lua#L13-L17

That is the idea yeah, if the plugin is not loaded then don't run the command. And by loaded, it means parsed the JSON file and knows about the dependencies.

**Comment by vuki656** [comment]
I'll have some time on Monday to debug this so ill look into it in more detail. 

If someone has a solution feel free to open a PR.

**Comment by ecosse3** [comment]
Same issue here. Getting `PackageInfo: Not in valid package.json file`.

**Comment by thomashoggard** [comment]
Experiencing the same issue as @ecosse3 with the error `PackageInfo: Not in valid package.json file`.  I'm using this plugin within a monorepo with turbo, not sure if that helps isolate the issue at all.

**Comment by vuki656** [comment]
I just merged #129. Not sure if that might help, please let me know.

Also, I removed the check on the `develop` branch, check if that fixes the issue.

**Comment by ecosse3** [comment]
@vuki656 Still getting the same error. Additionally on `develop` branch getting:

![image](https://user-images.githubusercontent.com/17691791/182953862-a3938a48-7984-4bf6-bfe4-2fd45ec67ed6.png)

**Comment by pedro757** [comment]
@ecosse3 do you have the latest version of this plugin?

**Comment by vuki656** [comment]
I guess the next step would be to implement a detailed logger and see what exactly is going on.

I'll put it on my to-do list.

If anyone wants to submit a PR, I'd be happy to review it.

**Comment by pedro757** [comment]
@vuki656 In my case it literally does nothing, it doesn't even show a message since you refactored the code.

**Comment by Nikola-Milovic** [comment]
`NVIM v0.8.0-dev+580-g45ba2e147`

Tried in multiple repos, same as Pedro I am getting absolutely no feedback, no errors, no output, running any of the commands results in `not in valid package.json file`.

Idk what could cause the conflict, maybe null-ls or jsonls?

**Comment by vuki656** [comment]
> `NVIM v0.8.0-dev+580-g45ba2e147`
> 
> Tried in multiple repos, same as Pedro I am getting absolutely no feedback, no errors, no output, running any of the commands results in `not in valid package.json file`.
> 
> Idk what could cause the conflict, maybe null-ls or jsonls?

Would you mind disabling those and seeing if it still happens?

**Comment by Nikola-Milovic** [comment]
@vuki656 disabling both didn't seem to fix the issue, still the same results

**Comment by ecosse3** [comment]
Now on `develop` branch, I'm getting different errors:

![image](https://user-images.githubusercontent.com/17691791/183389990-ccfdfcf8-9d64-4361-8988-4ef6100153fe.png)

NVIM v0.8.0-dev-2239-g85ad0e6b4

**Comment by Reicr** [comment]
I think the way of registering the auto commands is flawed. Since you are always using the same group, every time a new auto command is registered, all previous auto commands will be deleted because of "autocmd!". I tested this and every time only the last registered auto command worked.

```lua
return function(event, command)
    vim.cmd("augroup " .. constants.AUTOGROUP)
    vim.cmd("autocmd!")
    vim.cmd("autocmd " .. event .. " * " .. command)
    vim.cmd("augroup end")
end
```

**Comment by vuki656** [comment]
> I think the way of registering the auto commands is flawed. Since it always uses the same group, every time a new auto command is registered, all previous auto commands will be deleted because of "autocmd!". I tested this and every time only the last registered auto command worked.
> 
> ```lua
> return function(event, command)
>     vim.cmd("augroup " .. constants.AUTOGROUP)
>     vim.cmd("autocmd!")
>     vim.cmd("autocmd " .. event .. " * " .. command)
>     vim.cmd("augroup end")
> end
> ```
> 
> This leads to the case that the "load_plugin()" function is never called and therefore the plugin never gets initialised resulting in the observed problems.

Oh, that's interesting, didn't know that.

Would you mind opening a PR with this fix?

**Comment by Reicr** [comment]
Well, while trying to implement a fix I ran into another problem. The plugin now initialises but is reset shortly after so that I'm back to square one. Couldn't figure out yet why that is the case.

**Comment by vuki656** [comment]
> Well, while trying to implement a fix I ran into another problem. The plugin now initialises but is reset shortly after so that I'm back to square one. Couldn't figure out yet why that is the case.

By reset you mean the autogroup clears or?

**Comment by Reicr** [comment]
I think the problem was in the or is the `__is_valid_package_json` function since the autocmds use the "*" to define on which files the commands should be triggered. Not sure what happened in the background but I guess he somehow got a buffer that wasn't a package.json and disabled the plugin again. After I changed the pattern for the autocmds to only trigger on package.json files it worked.

**Comment by vuki656** [comment]
@pedro757 @piersolenski @zeitchef @thomashoggard 

Can you check if #130 solves the issue?

**Comment by ecosse3** [comment]
@vuki656 Works great to me now! I just noticed funny that during actions of package-info.nvim in status bar my text is mirrored: 
![image](https://user-images.githubusercontent.com/17691791/188323966-88409133-b642-4f3a-8de8-3995833617f9.png)

Rest works well

**Comment by Reicr** [comment]
Did not not touch that and it also works fine for me. I guess that's a separate problem. Although it should be confirmed, that this is actually a problem of the plugin and not just a problem of the status bar.

**Comment by krevativ** [comment]
I still have this issue and was looking into the root cause. I'm using npm workspaces and have a directory structure similar to this:

```
root/
  backend/
  frontend-workspace/
    app/
      package.json
    package.json
```

When I open frontend-workspace directly and open app/package.json, everithing works fine. But when I open the root directory first and then open frontend-workspace/app/package.json the plugin does nothing. Hope it can help someone.

**Comment by Reicr** [comment]
That is a different problem but it is certainly rather annoying. I opened up a pull request to fix this (#132). Feel free to test it.

**Comment by vuki656** [comment]
> I still have this issue and was looking into the root cause. I'm using npm workspaces and have a directory structure similar to this:
> 
> ```
> root/
>   backend/
>   frontend-workspace/
>     app/
>       package.json
>     package.json
> ```
> 
> When I open frontend-workspace directly and open app/package.json, everithing works fine. But when I open the root directory first and then open frontend-workspace/app/package.json the plugin does nothing. Hope it can help someone.

This is due to #114. Can you try @Reicr PR and see if it works now?

**Comment by krevativ** [comment]
@vuki656 I have tried @Reicr version ("feature/use-cwd-of-package-json" branch) and it works now. Thanks for the work, this was very annoying.
